config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  root to: 'welcome#index'

  get 'my-counters', to: 'buttons#personal'
  resources :buttons
end

app/models/button.rb
class Button < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :buttons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/buttons_controller.rb
class ButtonsController < ApplicationController

  def index
	@buttons = Button.all
  end

  def new
  	@button = Button.new
  end

  def create
  	@button = Button.new(button_params)
    @button.user_id = current_user.id
  	if @button.save
  		redirect_to my_counters_path, notice: "Your new Button was added."
  	else
  		flash[:error] = "Error creating button. Please try again."
  		redirect_to my_counters_path
  	end
  end

  def destroy
    @button = Button.find(params[:id])
    if @button.destroy
      redirect_to my_counters_path, notice: "Button was destroyed successfully."
    else
      flash[:error] = "There was an error in destoying this button. Please try again."
      redirect_to my_counters_path
    end
  end

  def reset
  	@buttons = Button.all #need all for current user!
  	if @buttons.reset
  	  @buttons.update_attribute(:hits, 0)
  	  redirect_to my_counters_path, notice: "All counters have been reset."
  	else
  	  flash[:error] = "There was an error in resetting the counters. Please try again."
      redirect_to my_counters_path
    end
  end

  def show
  	@button = Button.find(params[:id])
  end

  def update
  	@button = Button.find(params[:id])
  	cur = @button.hits
  	new_hit = cur + 1
  	if @button.update_attributes(button_params)
  	  @button.update_attribute(:hits, new_hit)
  	  redirect_to my_counters_path, notice: "All counters have been reset."
  	else
  	  flash[:error] = "There was an error in resetting the counters. Please try again."
      redirect_to my_counters_path
    end
  end


  def button_params
    params.require(:button).permit(:title, :hits, :user_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/buttons/_personalbuttons.html.erb
<% mybuttons = Button.joins(:user).where({user_id: current_user}) %>

<% if mybuttons.count > 0 %>
	<ul class="no-bull">
	<% mybuttons.each do |button| %>
		<h4>		
			<li>
				<div class="del-button pull-left">
				<%# if policy(mark).destroy? %>
					<%= link_to "", button, method: :delete, class: 'glyphicon glyphicon-remove-circle red' %>
				<%# end %>
				</div>

				<% form_for button do |f| %>
					<% button.increment!(:hits) %>
					<%= f.submit "#{button.title}", class: 'btn btn-primary' %>
				<% end %>

				<div class="hit-count pull-left">
					<strong><%= button.hits %></strong>
				</div>
			</li>
		</h4>
	<% end %>
	</ul>
<% end %>

app/views/buttons/personal.html.erb
<h1><%= current_user.name %> Counter Sandbox</h1>

<div class="row">

	<div class="col-md-6">
		<div class="media">
			<div class="media-body">
				<h4 class="media-heading">
					<%= render partial: 'personalbuttons' %>
				</h4>
			</div>
		</div>
	</div>

	<div class="col-md-6">
		<%#= render partial: 'bookmarks/new' %>
		<%#= render partial: 'topics/new' %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <meta name="viewport" content="width=device-width, inital-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<ul class="nav nav-tabs">
			<li><%= link_to "Home", welcome_index_path %></li>
			<li><%= link_to "GitHub", "https://github.com/kellobri/custom-countersApp" %></li>
			<div class="pull-right user-info">
				<% if current_user %>
					Hello <%= link_to current_user.name || current_user.email, edit_user_registration_path %>!  
					<%#= link_to "Your Counters", my_counters_path, class: 'btn btn-primary btn-xs' %>
					<%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-warning btn-xs' %>
				<% else %>
					<%= link_to "Sign In", new_user_session_path %> or 
					<%= link_to "Sign Up", new_user_registration_path %>
				<% end %>
			</div>
		</ul>

	<% if flash[:notice] %>
		<div class="alert alert-success">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:notice] %>
		</div>
	<% elsif flash[:error] %>
		<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:error] %>
		</div>
	<% elsif flash[:alert] %>
		<div class="alert alert-warning">
			<button type="button" class="close" data-dissmiss="alert">&times;</button>
			<%= flash[:alert] %>
		</div>
	<% end %>

	<%= yield %>
	</div>

</body>
</html>

app/views/welcome/index.html.erb
<div class="row">
	<div class="col-md-6">
		<h1>Custom Counter Buttons</h1>
		<p>Build and control your own custom counter buttons.</p>
		<% if current_user %>
			<h4 class="some-space">
			Go to 
			<%#= link_to "Your Counter Sandbox", my_counters_path, class: 'btn btn-info btn-lg' %>
			</h4>
		<% end %>
	</div>
</div>